### ISSUE TITLE
go get private repo via goproxy failed

### ISSUE THREAD

**Issue by WisperDin** [goproxyio/goproxy#124]
## environment
go version go1.13.3 darwin/amd64

## my goproxy configure:

```yml
version: "2"
services:
  goproxy:
    image: goproxy/goproxy:latest
    command: '-listen=0.0.0.0:8081 -cacheDir=/ext -proxy https://goproxy.io -exclude "*.company.com"'
    ports:
      - "8081:8081"
    volumes:
      - ./cacheDir:/ext
```

## when I run command in local
` GOPROXY=http://127.0.0.1:8081 go get -u -v  xxx.company.com/golang/xxxx`

I get response:
` reading http://127.0.0.1:8081/xxx.company.com/golang/xxxx/@v/list: 404 Not Found`

and I access the url get:
```sh
go list -m -json -versions xxx.company.com/golang/xxxx@latest:
go list -m: not using modules
```

and I run the command in local: `go list -m -json -versions ... ` , it perform normal and get the json

## how I fix it
add the environment variables: `GO111MODULE=on`， so that go can run go list with module, get the private repo version
